[build]
command = "dotnet build && dotnet publish --configuration Release"
publish = "./PrimusDb/bin/Release/net6.0/publish"

[functions]
include = "api/functions"

[[redirects]]
from = "/*"
to = "/api"
status = 301
